# Generated by Django 6.0 on 2025-12-15 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_invoice_discount_amount_invoice_insurance_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('neurotoxin', 'Botulinum Toxin (Neurotoxin)'), ('ha_filler', 'Hyaluronic Acid Filler'), ('bio_filler', 'Biostimulatory Filler'), ('suture', 'Suture/Thread'), ('consumable', 'Consumable (Syringe/Needle)'), ('prescription', 'Topical/Rx (Prescription)'), ('equipment', 'Equipment/Tool'), ('cleaning', 'Cleaning/Sterilization'), ('other', 'Other')], default='other', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('vial', 'Vial'), ('unit', 'Unit'), ('syringe', 'Syringe'), ('ml', 'ml'), ('box', 'Box'), ('kit', 'Kit'), ('packet', 'Packet'), ('set', 'Set'), ('pack', 'Pack'), ('tube', 'Tube'), ('bottle', 'Bottle'), ('jar', 'Jar'), ('mg', 'mg'), ('item', 'Item'), ('wipe', 'Wipe'), ('gallon', 'Gallon')], default='unit', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('linked_service', models.CharField(blank=True, max_length=200)),
                ('min_stock_level', models.PositiveIntegerField(default=5)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('add', 'Stock Added'), ('use', 'Stock Used'), ('adjust', 'Manual Adjustment'), ('expired', 'Expired/Disposed')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clinic.inventoryitem')),
            ],
        ),
    ]
