# Generated by Django 6.0 on 2025-12-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_inventoryitem_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('lab', 'Lab Test/Scan'), ('document', 'Document'), ('before_after', 'Before & After')], default='photo', max_length=20)),
                ('file_url', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='clinic.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clinic.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
