# Generated by Django 6.0 on 2025-12-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_patient_email_patient_medical_history_patient_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_area', models.CharField(max_length=200)),
                ('skin_type', models.CharField(choices=[('I', 'Type I - Very Fair'), ('II', 'Type II - Fair'), ('III', 'Type III - Medium'), ('IV', 'Type IV - Olive'), ('V', 'Type V - Brown'), ('VI', 'Type VI - Dark Brown/Black')], max_length=5)),
                ('intensity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Medium', max_length=20)),
                ('passes', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('post_care_instructions', models.TextField(blank=True)),
                ('consumables_used', models.TextField(blank=True)),
                ('session_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laser_session', to='clinic.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laser_sessions', to='clinic.patient')),
            ],
        ),
    ]
