# Generated by Django 6.0 on 2025-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_medicalcondition_surgerytype_alter_allergy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked-in'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('absent', 'Absent'), ('rescheduled', 'Rescheduled')], default='booked', max_length=20),
        ),
    ]
