# Generated by Django 5.2.12 on 2026-04-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
