# Generated by Django 5.2.12 on 2026-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_medication_category_medication_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('concept_type', models.CharField(db_index=True, max_length=50)),
                ('ontology', models.CharField(db_index=True, max_length=50)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='primary_disease_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='primary_disease_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='primary_disease_ontology',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
