# Generated by Django 5.2.12 on 2026-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_medicalconcept_medicalrecord_primary_disease_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='location_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='location_labels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='severity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptom_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptom_labels',
            field=models.TextField(blank=True),
        ),
    ]
